version: "3"
services:
  alg-wiki-dev:
    stdin_open: true
    tty: true
    container_name: alg-wiki-dev
    build: .
    ports:
      - "11037:11037"
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES:-dynamodb}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - PORT_WEB_UI=${PORT_WEB_UI-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - .:/workspace/alg-wiki
      - ./node_modules_docker:/workspace/alg-wiki/node_modules
      - "${TMPDIR:-./.localstack_cache}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
