[build]
  command = "yarn workspace @alg-wiki/website build --output-path ../dist-netlify/assets/"
  publish = "packages/website/dist-netlify/"

[[redirects]]
  from = "/*"
  to = "/assets/entry.html"
  status = 200
